// ContentIntel — Research editor (admin-only). Edits the in-memory research,
// previews it live, and exports an updated research.js to commit.
//
// HONEST NOTE: on a static site this gate is obscurity-level — anyone can read
// the source. The REAL protection is that the live site only changes when YOU
// commit research.js. The editor here just hides the UI from normal visitors
// and lets you produce the file without hand-editing JSON.

const LS_ADMIN = "ci_admin";
function isAdmin() {
  try {
    if (localStorage.getItem(LS_ADMIN) === "1") return true;
    const p = new URLSearchParams(location.search).get("admin");
    if (p && p === window.ADMIN_PASS) { localStorage.setItem(LS_ADMIN, "1"); return true; }
  } catch (e) {}
  return false;
}
function promptAdmin() {
  const p = window.prompt("Research editor passphrase:");
  if (p === window.ADMIN_PASS) { try { localStorage.setItem(LS_ADMIN, "1"); } catch (e) {} return true; }
  if (p != null) window.alert("Wrong passphrase.");
  return false;
}
function exitAdmin() { try { localStorage.removeItem(LS_ADMIN); } catch (e) {} }

// current research = override (edited) or the file's window.CI_RESEARCH
function currentResearch() {
  return window.__CI_RESEARCH_OVERRIDE || window.CI_RESEARCH || {};
}
function serializeResearch(obj) {
  return "/* ContentIntel research data — generated by the in-app Research editor.\n" +
    "   Commit this file and redeploy; the app code does not change. */\n\n" +
    "window.CI_RESEARCH = " + JSON.stringify(obj, null, 2) + ";\n";
}

function ResearchTab({ onClose, onNav }) {
  const mood = "navy";
  const m = window.MOODS[mood];
  const SECTIONS = ["core", "script", "thumbnail", "title", "ads"];
  const LABELS = { core: "Global · all checks", script: "Script", thumbnail: "Thumbnail", title: "Title", ads: "Ads" };

  const [data, setData] = React.useState(() => JSON.parse(JSON.stringify(currentResearch())));
  const [active, setActive] = React.useState("core");
  const [priv, setPriv] = React.useState(window.hasLocalResearch());
  const [raw, setRaw] = React.useState(false);
  const [rawText, setRawText] = React.useState("");
  const [msg, setMsg] = React.useState("");

  const seg = data[active] || {};

  function setField(type, field, value) {
    setData(d => ({ ...d, [type]: { ...(d[type] || {}), [field]: value } }));
  }
  function setRubric(type, idx, key, value) {
    setData(d => {
      const rub = [...((d[type] || {}).rubric || [])];
      rub[idx] = { ...rub[idx], [key]: value };
      return { ...d, [type]: { ...(d[type] || {}), rubric: rub } };
    });
  }
  function addRubric(type) {
    setData(d => ({ ...d, [type]: { ...(d[type] || {}), rubric: [...((d[type] || {}).rubric || []), { name: "New dimension", what: "" }] } }));
  }
  function delRubric(type, idx) {
    setData(d => ({ ...d, [type]: { ...(d[type] || {}), rubric: ((d[type] || {}).rubric || []).filter((_, i) => i !== idx) } }));
  }

  function savePrivate() {
    let next = data;
    if (raw) {
      try { next = JSON.parse(rawText); setData(next); } catch (e) { setMsg("Invalid JSON: " + e.message); return; }
    }
    window.saveLocalResearch(next);
    setPriv(true);
    setMsg("Saved privately to this browser — your analyses use it now. Other visitors are unaffected until you Download + redeploy.");
    setTimeout(() => setMsg(""), 5000);
  }
  function clearPrivate() {
    window.clearLocalResearch();
    setData(JSON.parse(JSON.stringify(window.CI_RESEARCH || {})));
    setPriv(false);
    setMsg("Cleared your private draft — back to the published research.js.");
    setTimeout(() => setMsg(""), 4000);
  }
  function download() {
    const obj = raw ? safeParse(rawText) : data;
    if (!obj) { setMsg("Fix the JSON before downloading."); return; }
    const blob = new Blob([serializeResearch(obj)], { type: "text/javascript" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a"); a.href = url; a.download = "research.js"; a.click();
    URL.revokeObjectURL(url);
    setMsg("Downloaded research.js — commit it to your repo and redeploy.");
    setTimeout(() => setMsg(""), 4000);
  }
  function safeParse(t) { try { return JSON.parse(t); } catch (e) { return null; } }
  function toggleRaw() {
    if (!raw) setRawText(JSON.stringify(data, null, 2));
    else { const o = safeParse(rawText); if (o) setData(o); }
    setRaw(r => !r);
  }

  return (
    <div className="ci-work wide" style={{ "--ci-accent": m.accentFrom, "--ci-glow": m.accentGlow }}>
      <div style={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", marginBottom: 18, flexWrap: "wrap", gap: 12 }}>
        <div>
          <Eyebrow mood={mood} glow>Admin · research {priv && "· private draft active"}</Eyebrow>
          <h2 className="ci-h2">Improve the research</h2>
          <p className="ci-sub" style={{ marginTop: 8 }}>
            Your private editing surface — invisible to anyone you share the link with. Add findings anytime; <b>Save (private)</b> keeps them in your browser and uses them in your own analyses straight away. When you want everyone to benefit, <b>Download research.js</b>, commit it and redeploy. The app code never changes.
          </p>
        </div>
        <div style={{ display: "flex", gap: 8 }}>
          {onNav && <button className="ci-copybtn" style={{ height: 34 }} onClick={() => onNav("train")}>🧠 Train from thumbnails →</button>}
          <button className="ci-copybtn" style={{ height: 34 }} onClick={toggleRaw}>{raw ? "Form view" : "Raw JSON"}</button>
          <button className="ci-copybtn" style={{ height: 34 }} onClick={() => { exitAdmin(); onClose(); }}>Lock & exit</button>
        </div>
      </div>

      <div className="ci-block" style={{ display: "flex", alignItems: "flex-start", gap: 12, marginBottom: 14, padding: "12px 16px" }}>
        <span className="ci-dot yellow" style={{ marginTop: 4 }} />
        <span style={{ fontSize: 12.5, color: "var(--text-3)", lineHeight: 1.5 }}>
          <b>How privacy works:</b> the Research tab + lock icon are hidden from normal visitors (they appear only after you unlock via <code>?admin=…</code> on your own browser). Drafts you <b>Save (private)</b> live only in your browser and never reach other users. Only <b>Download research.js → commit</b> publishes to everyone. Note: once published, research.js ships to the browser, so don't store secrets here — it's evaluation methodology, not credentials.
        </span>
      </div>

      {!raw ? (
        <>
          <div className="ci-chiprow" style={{ marginBottom: 14 }}>
            {SECTIONS.map(t => (
              <button key={t} className={"pill" + (active === t ? " active" : "")} onClick={() => setActive(t)} style={{ height: 32 }}>{LABELS[t]}</button>
            ))}
          </div>

          {active === "core" ? (
            <Block title="Global research context" desc="Shared by EVERY check — the universal attention/virality science + how to adapt to any language, region and niche. This is prepended to every analysis." mood={mood}>
              <textarea className="ci-textarea" style={{ minHeight: 380, fontFamily: "var(--font-mono)", fontSize: 12.5, lineHeight: 1.6 }}
                value={data.core || ""} onChange={e => setData(d => ({ ...d, core: e.target.value }))}
                placeholder="Paste the research that should inform all four checks…" />
            </Block>
          ) : (
          <>
          <Block title={`${LABELS[active]} · methodology`} desc="This becomes Claude's evaluation framework for this specific check." mood={mood}>
            <textarea className="ci-textarea" style={{ minHeight: 260, fontFamily: "var(--font-mono)", fontSize: 12.5, lineHeight: 1.6 }}
              value={seg.systemGuidance || ""} onChange={e => setField(active, "systemGuidance", e.target.value)}
              placeholder="Frameworks, data points, do's and don'ts, examples…" />
          </Block>

          <Block title={`${LABELS[active]} · scoring rubric`} desc="The dimensions Claude grades 0–100" mood={mood}
            right={<button className="ci-copybtn" style={{ height: 28 }} onClick={() => addRubric(active)}>+ Add</button>}>
            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
              {(seg.rubric || []).map((r, i) => (
                <div key={i} style={{ display: "grid", gridTemplateColumns: "180px 1fr 30px", gap: 10, alignItems: "start" }}>
                  <input className="ci-input" value={r.name || ""} onChange={e => setRubric(active, i, "name", e.target.value)} placeholder="Dimension" />
                  <input className="ci-input" value={r.what || ""} onChange={e => setRubric(active, i, "what", e.target.value)} placeholder="What it measures" />
                  <button className="ci-copybtn" style={{ height: 44, padding: "0 9px" }} onClick={() => delRubric(active, i)}>✕</button>
                </div>
              ))}
            </div>
          </Block>

          <Block title={`${LABELS[active]} · extra notes`} mood={mood}>
            <input className="ci-input" value={seg.notes || ""} onChange={e => setField(active, "notes", e.target.value)} placeholder="Optional extra instruction appended to the prompt" />
          </Block>
          </>
          )}
        </>
      ) : (
        <Block title="Raw research JSON" desc="Edit the whole object directly" mood={mood}>
          <textarea className="ci-textarea" style={{ minHeight: 460, fontFamily: "var(--font-mono)", fontSize: 12, lineHeight: 1.55 }}
            value={rawText} onChange={e => setRawText(e.target.value)} spellCheck={false} />
        </Block>
      )}

      <div style={{ display: "flex", alignItems: "center", gap: 14, marginTop: 16, flexWrap: "wrap" }}>
        <GlowButton mood={mood} onClick={savePrivate}>Save (private to this browser)</GlowButton>
        <GlowButton mood="burgundy" onClick={download}>↓ Download research.js (publish to all)</GlowButton>
        {priv && <button className="ci-copybtn" style={{ height: 38 }} onClick={clearPrivate}>Clear private draft</button>}
        {msg && <span style={{ fontSize: 12.5, color: "var(--text-2)", maxWidth: 360, lineHeight: 1.4 }}>{msg}</span>}
      </div>
    </div>
  );
}

Object.assign(window, { isAdmin, promptAdmin, exitAdmin, ResearchTab });

