// ContentIntel — Research editor (admin-only). Edits the in-memory research,
// previews it live, and exports an updated research.js to commit.
//
// HONEST NOTE: on a static site this gate is obscurity-level — anyone can read
// the source. The REAL protection is that the live site only changes when YOU
// commit research.js. The editor here just hides the UI from normal visitors
// and lets you produce the file without hand-editing JSON.

const LS_ADMIN = "ci_admin";
function isAdmin() {
  try {
    if (localStorage.getItem(LS_ADMIN) === "1") return true;
    const p = new URLSearchParams(location.search).get("admin");
    if (p && p === window.ADMIN_PASS) { localStorage.setItem(LS_ADMIN, "1"); return true; }
  } catch (e) {}
  return false;
}
function promptAdmin() {
  const p = window.prompt("Research editor passphrase:");
  if (p === window.ADMIN_PASS) { try { localStorage.setItem(LS_ADMIN, "1"); } catch (e) {} return true; }
  if (p != null) window.alert("Wrong passphrase.");
  return false;
}
function exitAdmin() { try { localStorage.removeItem(LS_ADMIN); } catch (e) {} }

// current research = override (edited) or the file's window.CI_RESEARCH
function currentResearch() {
  return window.__CI_RESEARCH_OVERRIDE || window.CI_RESEARCH || {};
}
function serializeResearch(obj) {
  return "/* ContentIntel research data — generated by the in-app Research editor.\n" +
    "   Commit this file and redeploy; the app code does not change. */\n\n" +
    "window.CI_RESEARCH = " + JSON.stringify(obj, null, 2) + ";\n";
}

function ResearchTab({ onClose }) {
  const mood = "navy";
  const m = window.MOODS[mood];
  const TYPES = ["script", "thumbnail", "title", "ads"];

  const [data, setData] = React.useState(() => JSON.parse(JSON.stringify(currentResearch())));
  const [active, setActive] = React.useState("script");
  const [raw, setRaw] = React.useState(false);
  const [rawText, setRawText] = React.useState("");
  const [msg, setMsg] = React.useState("");

  const seg = data[active] || {};

  function setField(type, field, value) {
    setData(d => ({ ...d, [type]: { ...(d[type] || {}), [field]: value } }));
  }
  function setRubric(type, idx, key, value) {
    setData(d => {
      const rub = [...((d[type] || {}).rubric || [])];
      rub[idx] = { ...rub[idx], [key]: value };
      return { ...d, [type]: { ...(d[type] || {}), rubric: rub } };
    });
  }
  function addRubric(type) {
    setData(d => ({ ...d, [type]: { ...(d[type] || {}), rubric: [...((d[type] || {}).rubric || []), { name: "New dimension", what: "" }] } }));
  }
  function delRubric(type, idx) {
    setData(d => ({ ...d, [type]: { ...(d[type] || {}), rubric: ((d[type] || {}).rubric || []).filter((_, i) => i !== idx) } }));
  }

  function applyLive() {
    let next = data;
    if (raw) {
      try { next = JSON.parse(rawText); setData(next); } catch (e) { setMsg("Invalid JSON: " + e.message); return; }
    }
    window.__CI_RESEARCH_OVERRIDE = next;
    setMsg("Applied for this session — analyses now use these edits. Download to make it permanent.");
    setTimeout(() => setMsg(""), 4000);
  }
  function download() {
    const obj = raw ? safeParse(rawText) : data;
    if (!obj) { setMsg("Fix the JSON before downloading."); return; }
    const blob = new Blob([serializeResearch(obj)], { type: "text/javascript" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a"); a.href = url; a.download = "research.js"; a.click();
    URL.revokeObjectURL(url);
    setMsg("Downloaded research.js — commit it to your repo and redeploy.");
    setTimeout(() => setMsg(""), 4000);
  }
  function safeParse(t) { try { return JSON.parse(t); } catch (e) { return null; } }
  function toggleRaw() {
    if (!raw) setRawText(JSON.stringify(data, null, 2));
    else { const o = safeParse(rawText); if (o) setData(o); }
    setRaw(r => !r);
  }

  return (
    <div className="ci-work wide" style={{ "--ci-accent": m.accentFrom, "--ci-glow": m.accentGlow }}>
      <div style={{ display: "flex", alignItems: "flex-end", justifyContent: "space-between", marginBottom: 18, flexWrap: "wrap", gap: 12 }}>
        <div>
          <Eyebrow mood={mood} glow>Admin · research</Eyebrow>
          <h2 className="ci-h2">Improve the research</h2>
          <p className="ci-sub" style={{ marginTop: 8 }}>
            This is your private editing surface. Edit the methodology Claude uses, click <b>Apply</b> to test it live, then <b>Download research.js</b> and commit it. The rest of the app never changes.
          </p>
        </div>
        <div style={{ display: "flex", gap: 8 }}>
          <button className="ci-copybtn" style={{ height: 34 }} onClick={toggleRaw}>{raw ? "Form view" : "Raw JSON"}</button>
          <button className="ci-copybtn" style={{ height: 34 }} onClick={() => { exitAdmin(); onClose(); }}>Lock & exit</button>
        </div>
      </div>

      <div className="ci-block" style={{ display: "flex", alignItems: "center", gap: 12, marginBottom: 14, padding: "12px 16px" }}>
        <span className="ci-dot yellow" />
        <span style={{ fontSize: 12.5, color: "var(--text-3)", lineHeight: 1.5 }}>
          Static-site note: this lock only hides the editor. The live site changes only when you commit <b>research.js</b> — so your research can't be altered by visitors.
        </span>
      </div>

      {!raw ? (
        <>
          <div className="ci-chiprow" style={{ marginBottom: 14 }}>
            {TYPES.map(t => (
              <button key={t} className={"pill" + (active === t ? " active" : "")} onClick={() => setActive(t)} style={{ height: 32, textTransform: "capitalize" }}>{t}</button>
            ))}
          </div>

          <Block title={`${active} · methodology`} desc="Paste your research here. This becomes Claude's evaluation framework for this check." mood={mood}>
            <textarea className="ci-textarea" style={{ minHeight: 260, fontFamily: "var(--font-mono)", fontSize: 12.5, lineHeight: 1.6 }}
              value={seg.systemGuidance || ""} onChange={e => setField(active, "systemGuidance", e.target.value)}
              placeholder="Frameworks, data points, do's and don'ts, examples…" />
          </Block>

          <Block title={`${active} · scoring rubric`} desc="The dimensions Claude grades 0–100" mood={mood}
            right={<button className="ci-copybtn" style={{ height: 28 }} onClick={() => addRubric(active)}>+ Add</button>}>
            <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>
              {(seg.rubric || []).map((r, i) => (
                <div key={i} style={{ display: "grid", gridTemplateColumns: "180px 1fr 30px", gap: 10, alignItems: "start" }}>
                  <input className="ci-input" value={r.name || ""} onChange={e => setRubric(active, i, "name", e.target.value)} placeholder="Dimension" />
                  <input className="ci-input" value={r.what || ""} onChange={e => setRubric(active, i, "what", e.target.value)} placeholder="What it measures" />
                  <button className="ci-copybtn" style={{ height: 44, padding: "0 9px" }} onClick={() => delRubric(active, i)}>✕</button>
                </div>
              ))}
            </div>
          </Block>

          <Block title={`${active} · extra notes`} mood={mood}>
            <input className="ci-input" value={seg.notes || ""} onChange={e => setField(active, "notes", e.target.value)} placeholder="Optional extra instruction appended to the prompt" />
          </Block>
        </>
      ) : (
        <Block title="Raw research JSON" desc="Edit the whole object directly" mood={mood}>
          <textarea className="ci-textarea" style={{ minHeight: 460, fontFamily: "var(--font-mono)", fontSize: 12, lineHeight: 1.55 }}
            value={rawText} onChange={e => setRawText(e.target.value)} spellCheck={false} />
        </Block>
      )}

      <div style={{ display: "flex", alignItems: "center", gap: 14, marginTop: 16, flexWrap: "wrap" }}>
        <GlowButton mood={mood} onClick={applyLive}>Apply for this session</GlowButton>
        <GlowButton mood="burgundy" onClick={download}>↓ Download research.js</GlowButton>
        {msg && <span style={{ fontSize: 12.5, color: "var(--text-2)" }}>{msg}</span>}
      </div>
    </div>
  );
}

Object.assign(window, { isAdmin, promptAdmin, exitAdmin, ResearchTab });
