#!/usr/bin/env python3
"""Build a self-contained @font-face stylesheet with the fonts base64-embedded.

Headless Chromium in this environment does not reliably fetch webfonts at render
time, so a carousel that links Google Fonts silently falls back to DejaVu Sans.
Embedding removes the network from the render path entirely.

Run once; commit the result:

    python3 scripts/fetch-fonts.py

Writes linkedin/assets/fonts.css. Reference it from a carousel with:

    <link rel="stylesheet" href="../../assets/fonts.css">

Defaults to the ContentIntel brand faces (see linkedin/brand.md). Override:

    python3 scripts/fetch-fonts.py "Inter:wght@400;700" "Fraunces:wght@700"
"""
import base64
import pathlib
import re
import sys
import urllib.request

DEFAULT_FAMILIES = [
    "Space Grotesk:wght@500;700",
    "Manrope:wght@500;600;800",
    "JetBrains Mono:wght@600",
]

# Only these subsets — latin covers the brand's needs and keeps the file small.
KEEP_SUBSETS = {"latin", "latin-ext"}

UA = ("Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

OUT = pathlib.Path(__file__).resolve().parent.parent / "linkedin" / "assets" / "fonts.css"


def get(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=60) as r:
        data = r.read()
    return data if binary else data.decode("utf-8")


def main(argv):
    families = argv[1:] or DEFAULT_FAMILIES
    query = "&".join("family=" + f.replace(" ", "+") for f in families)
    url = f"https://fonts.googleapis.com/css2?{query}&display=swap"

    print(f"fetching {len(families)} families…")
    try:
        css = get(url)
    except Exception as e:
        print(f"error: could not reach Google Fonts: {e}", file=sys.stderr)
        return 1

    # css2 emits a comment naming the subset before each @font-face block.
    blocks = re.split(r"/\*\s*([a-z0-9-]+)\s*\*/", css)
    out, embedded, skipped = [], 0, 0

    for i in range(1, len(blocks) - 1, 2):
        subset, block = blocks[i], blocks[i + 1]
        if subset not in KEEP_SUBSETS:
            skipped += 1
            continue
        m = re.search(r"url\((https://fonts\.gstatic\.com/[^)]+)\)", block)
        if not m:
            continue
        try:
            raw = get(m.group(1), binary=True)
        except Exception as e:
            print(f"  warn: {m.group(1).rsplit('/', 1)[-1]}: {e}", file=sys.stderr)
            continue
        uri = "data:font/woff2;base64," + base64.b64encode(raw).decode("ascii")
        out.append(block.replace(m.group(1), uri).strip())
        embedded += 1
        fam = re.search(r"font-family:\s*'([^']+)'", block)
        wt = re.search(r"font-weight:\s*(\d+)", block)
        print(f"  {fam.group(1) if fam else '?'} {wt.group(1) if wt else ''} "
              f"({len(raw) / 1024:,.0f} KB)")

    if not embedded:
        print("error: embedded nothing — the Google Fonts response may have changed.",
              file=sys.stderr)
        return 1

    OUT.parent.mkdir(parents=True, exist_ok=True)
    header = ("/* Generated by scripts/fetch-fonts.py — do not edit.\n"
              f"   Families: {', '.join(families)}\n"
              "   Fonts are embedded so headless Chromium never needs the network. */\n\n")
    OUT.write_text(header + "\n\n".join(out) + "\n", encoding="utf-8")
    print(f"\n{OUT}  ({embedded} faces, {skipped} non-latin subsets skipped, "
          f"{OUT.stat().st_size / 1024:,.0f} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
